### PR TITLE
Revive feedstock

### PR DESCRIPTION
**Pull request by h-vetinari**
It's built with such old pins that it's effectively uninstallable

### CODE REVIEW

**Comment by h-vetinari** [comment]
As far as I can tell, `sdl2_mixer.dll` is built, but not the `.lib` file, which most likely means that the symbols are not exported with `__declspec(dllexport)` etc, and doing that manually is a major PITA. Upstream now provides CMake integration as of more recent builds (thus allowing to solve the problem by `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` without touching the sources), and I'm planning to retry windows support once the version upgrade bot comes around after this is merged.

**Comment by h-vetinari** [comment]
Ugh, just saw that upstream [vendors](https://github.com/libsdl-org/SDL_mixer/tree/release-2.0.4/external) a lot of the required dependencies, which is presumably where the hard pins came from. I still think we should rely on the run_exports of conda(-forge) for this, but not sure how we can test this properly. This also looks like it should become better with more recent releases though.

Perhaps it's not worth trying to rebuild a 4 year old release after all (wanted to start with what's already there).

**Review by matham — APPROVED** [review]
Is it all good ready to be merged?

**Comment by h-vetinari** [comment]
> Is it all good ready to be merged?

I did one more pass to check the diff (& the run-exports of the host-requirements), I think it should be good now. 🙃

**Review by matham — APPROVED** [review]

**Comment by matham** [comment]
Thanks for all your work!!

**Comment by h-vetinari** [comment]
Thanks for the review & merge!

Let's hope things keep running as smoothly as before even after jumping across a 4 year gap 😅

**Pull request merged**
